FROM node:18-alpine

WORKDIR /app

COPY app/package*.json ./
RUN npm install --production

COPY app/index.js ./index.js

ARG APP_VERSION=A
ENV APP_VERSION=${APP_VERSION}

EXPOSE 3000
CMD ["node", "index.js"]
